server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TeleBot
    username: TeleBot
    password: 4rfgt5
  liquibase:
    enabled: true

bot:
  name: lyjustic_edutestbot
  token: ${TOKEN}
  url: https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&exclude={exclude}&appid={appid}&lang={lang}&units={units}
  appid: 993f740fb37f4a0c5478a56034b089d2